### ISSUE TITLE
node_modules in repository

### ISSUE THREAD

**Issue by TheRealStingo** [Eve-SatOrU/EventPulse#1]
its not a good practice to include node_modules when u publish your branch , always make sure to ass node_modules to .gitignore file

**Comment by Eve-SatOrU** [comment]
Thank you for bringing this to my attention. I've recently updated my project and removed the node_modules directory from the repository. It should no longer be included in the branch I'm publishing.

<h3>If you encounter any other issues or have further suggestions, please feel free to let me know ^^ .</h3>
